### ISSUE TITLE
一直不动

### ISSUE THREAD

**Issue by jj89757hhb** [MeandNi/Flutter_ZhiHu#1]
Error output from CocoaPods:
↳
    /Users/xuetianhhb/.rvm/gems/ruby-2.2.2@global/gems/gh_inspector-1.0.3/lib/gh_inspector/sidekick.rb:83:in `parse_results': undefined method `map' for nil:NilClass (NoMethodError)
    	from /Users/xuetianhhb/.rvm/gems/ruby-2.2.2@global/gems/gh_inspector-1.0.3/lib/gh_inspector/sidekick.rb:32:in `search'
    	from /Users/xuetianhhb/.rvm/gems/ruby-2.2.2@global/gems/gh_inspector-1.0.3/lib/gh_inspector/inspector.rb:65:in `search_query'
    	from /Users/xuetianhhb/.rvm/gems/ruby-2.2.2@global/gems/gh_inspector-1.0.3/lib/gh_inspector/inspector.rb:59:in `search_exception'
    	from /Users/xuetianhhb/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.2.1/lib/cocoapods/user_interface/error_report.rb:119:in `search_for_exceptions'
    	from /Users/xuetianhhb/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.2.1/lib/cocoapods/command.rb:67:in `report_error'
    	from /Users/xuetianhhb/.rvm/gems/ruby-2.2.2@global/gems/claide-1.0.1/lib/claide/command.rb:396:in `handle_exception'
    	from /Users/xuetianhhb/.rvm/gems/ruby-2.2.2@global/gems/claide-1.0.1/lib/claide/command.rb:337:in `rescue in run'
    	from /Users/xuetianhhb/.rvm/gems/ruby-2.2.2@global/gems/claide-1.0.1/lib/claide/command.rb:325:in `run'
    	from /Users/xuetianhhb/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.2.1/lib/cocoapods/command.rb:52:in `run'
    	from /Users/xuetianhhb/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.2.1/bin/pod:55:in `<top (required)>'
    	from /usr/local/bin/pod:23:in `load'
    	from /usr/local/bin/pod:23:in `<main>'
    	from /Users/xuetianhhb/.rvm/gems/ruby-2.2.2@global/bin/ruby_executable_hooks:15:in `eval'
    	from /Users/xuetianhhb/.rvm/gems/ruby-2.2.2@global/bin/ruby_executable_hooks:15:in `<main>'

Error launching application on iPhone 8.

**Comment by MeandNi** [comment]
flutter doctor 检查一下环境，是第一次运行 flutter 项目吗？

**Comment by jj89757hhb** [comment]
之前有运行其他的

**Comment by MeandNi** [comment]
> 之前有运行其他的

检查一下网络，还是不能运行吗
