### ISSUE TITLE
run的时候报错

### ISSUE THREAD

**Issue by hjue** [MeandNi/Flutter_ZhiHu#10]
<img width="731" alt="image" src="https://user-images.githubusercontent.com/1135045/70371868-6226bb80-1913-11ea-9cec-26208a9c774b.png">

flutter doctor 没问题，可以运行用flutter create xxxx的项目

不过运行这个项目报错：

<img width="917" alt="image" src="https://user-images.githubusercontent.com/1135045/70371895-ae71fb80-1913-11ea-95f9-e868e508e7fb.png">

**Comment by MeandNi** [comment]
依赖库版本问题，已更新
