### ISSUE TITLE
项目导入安卓studio报红

### ISSUE THREAD

**Issue by YuPf1989** [MeandNi/Flutter_ZhiHu#2]
我也是刚接触flutter项目，只是简单的配置了下flutter和studio，导入项目后见下提示：
![default](https://user-images.githubusercontent.com/17273260/52926493-fa49b900-3370-11e9-8b0a-02c9f8f48fec.png)
不知道该如何修改呢？
ps：我自己用studio创建flutter项目是可以运行的，也在studio配置了flutter、dart路径。

**Comment by MeandNi** [comment]
应该是你的第三方包没有导入完全 执行 flutter packages get 试试

**Comment by YuPf1989** [comment]
确实有用，另外还有些报错：
1.提示类型应为double，实际为int
![default](https://user-images.githubusercontent.com/17273260/52932656-6cc79280-338b-11e9-97f1-5c1d8c7c97bd.png)
2.Future类未定义
![default](https://user-images.githubusercontent.com/17273260/52932671-7b15ae80-338b-11e9-9a94-d7844db6568b.png)
应该怎么做呢？

**Comment by MeandNi** [comment]
> 确实有用，另外还有些报错：
> 1.提示类型应为double，实际为int
> ![default](https://user-images.githubusercontent.com/17273260/52932656-6cc79280-338b-11e9-97f1-5c1d8c7c97bd.png)
> 2.Future类未定义
> ![default](https://user-images.githubusercontent.com/17273260/52932671-7b15ae80-338b-11e9-9a94-d7844db6568b.png)
> 应该怎么做呢？

0 -> 0.0
导入异步库，编辑器 alt+enter

**Comment by YuPf1989** [comment]
关于第一个，我知道可以这样改，但是你项目里边这样写为何可以呢？与flutter版本还是库有关系？主要是一个个手改太麻烦了，第二个解决了

**Comment by YuPf1989** [comment]
改完之后可以运行了，感觉flutter还是挺卡顿的......

**Comment by MeandNi** [comment]
我这边不是浮点是可以，可能是编译后有之前的代码...你真机测试一下。flutter还是很流畅的，debug版本会卡顿 打包过后会流畅


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by YuPf1989** [comment]
今天再次打开项目，发现运行不了了，提示如下信息：
![default](https://user-images.githubusercontent.com/17273260/53139931-17c39080-35c6-11e9-96a2-26f813c7f867.png)
貌似是app下的build.gradle中配置：
![default](https://user-images.githubusercontent.com/17273260/53140029-6a9d4800-35c6-11e9-9ccf-f8be261ee6dc.png)
没有配置signingConfigs，但是我自己的项目也是没有signingConfigs，但是可以直接真机运行......

**Comment by MeandNi** [comment]
> 今天再次打开项目，发现运行不了了，提示如下信息：
> ![default](https://user-images.githubusercontent.com/17273260/53139931-17c39080-35c6-11e9-96a2-26f813c7f867.png)
> 貌似是app下的build.gradle中配置：
> ![default](https://user-images.githubusercontent.com/17273260/53140029-6a9d4800-35c6-11e9-9ccf-f8be261ee6dc.png)
> 没有配置signingConfigs，但是我自己的项目也是没有signingConfigs，但是可以直接真机运行......

我这边没有这种情况啊～～重新 clone 一下试试，你有修改过代码吗？
