### ISSUE TITLE
Run不起来，看起来好像三方库改了参数有问题？

### ISSUE THREAD

**Issue by GengJian** [MeandNi/Flutter_ZhiHu#5]
Compiler message:
lib/idea/idea_header.dart:139:9: Error: No named parameter with the name 'interval'.
        interval: const Duration(seconds: 5),
        ^^^^^^^^
file:///Users/mac/.pub-cache/hosted/pub.flutter-io.cn/carousel_slider-1.3.0/lib/carousel_slider.dart:9:3: Context: Found this candidate, but
the arguments don't match.
  CarouselSlider({
  ^
Compiler failed on /Users/mac/GitSpace/FlutterProjects/FlutterZhiHu/lib/main.dart
Error launching application on iPhone 5s.

**Comment by MeandNi** [comment]
const Duration(seconds: 5) 改成 const Duration(seconds: 5.0) 就好了，哟使用浮点数
