### ISSUE TITLE
没跑起来

### ISSUE THREAD

**Issue by anjiuzhe** [MeandNi/Flutter_ZhiHu#7]
![image](https://user-images.githubusercontent.com/30287547/59506054-db4fd380-8ed9-11e9-871c-36c95d06a9ed.png)
![image](https://user-images.githubusercontent.com/30287547/59506072-e7d42c00-8ed9-11e9-85be-2946beb8415c.png)

**Comment by MeandNi** [comment]
已经解决，升级一下依赖就好。
