### ISSUE TITLE
跑不起来，不准备解决了么...

### ISSUE THREAD

**Issue by lynxme** [MeandNi/Flutter_ZhiHu#9]

**Comment by MeandNi** [comment]
已经解决，升级一下依赖就好。

**Comment by andrewhunter0** [comment]
把android目录/app下的compileSdkVersion改成28...

**Comment by zombiu** [comment]
> 把android目录/app下的compileSdkVersion改成28...

谢谢大佬，搞了大半天，终于能跑了！
